# ============================================================
# PISTACHIO â€” Eval Dataset Config
# Points to your EVAL folder (20% of captioned images)
# Used for convergence graphs on wandb
# ============================================================

resolutions = [512]

enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7

frame_buckets = [1]

[[directory]]
path = '/workspace/dataset/eval'
num_repeats = 1
